### PR TITLE
Remove most the locking around setting slf to done

### PR DESCRIPTION
**Pull request by lwahlmeier**

### CODE REVIEW

**Comment by jentfoo** [comment]
I have not looked at the latest PR yet, but looks like there is some unit test failures:
https://threadly.ci.cloudbees.com/job/threadly-master/552/testReport/

**Comment by lwahlmeier** [comment]
Maybe I am reading this wrong but they look like they should have been failing before.   The default constructor for SLF is to throw if its already set...  All these tests seem to be these cases:

  @Test
  public void cancelTest() {
    assertTrue(slf.cancel(false));
    assertFalse(slf.cancel(false));
    
    assertTrue(slf.isCancelled());
    assertTrue(slf.isDone());
  }

The 2nd one should throw with the alreadyDone because it is.  I see why this was not happening before since we did an if(isDone) before we try to set it, but this seems somewhat more right in a way.  What are your thoughts?

**Comment by jentfoo** [comment]
You saved me some time, I never looked at what was failing or the code (I will later this weekend, I promise).

Cancel is different than setResult and setFailure.  I stuck with java.util.concurrent.Future's definition of cancel which is that it never throws (even if the SLF was constructed with a true).  It just returns a false.  I thought this made the most sense in case someone wants to pass the future into another class or library.  Or maybe it was returned to them and they did not even know it's an SLF.

So I think it should be a special case.  In the previous implementation that's why we checked done before we called into setDone

**Comment by lwahlmeier** [comment]
getting ready to push up the fix.  I am sometimes getting a unit test failure on
org.threadly.util.debug.ProfilerTest > startWitExecutorTest FAILED
Its a pure TimedOutException failure and only seems to happen on my laptop rarely but when its under heavier load.  Just more of an FYI then anything else.

**Comment by jentfoo** [comment]
For piece of mind would you set result and failure as volatile.  I don't think it should be necessary due to the synchronization that occurs afterwards, but technically it could be.

Also would you mind just passing a boolean into setDone to indicate if it should throw or not if already set.  That way in cancel we don't have to have a catch clause that will be impossible to unit test.

Minor nitpicks I know, but after that I think this looks really good.  Thanks for your help!

**Comment by lwahlmeier** [comment]
should all be good now. Let me know if you think of anything else.

**Comment by jentfoo** [comment]
Looks great, thank you!

**Pull request merged**
