### PR TITLE
Interface rename: Dropped the "Interface" suffix

### PR DESCRIPTION
**Pull request by jentfoo**
Originally I had put "Interface" at the end of all interface names so it was obvious what they were (with the exception of ListenableFuture which has no such convention).
The goal was to make it easy when looking through the javadocs to know what was an implementation, vs an interface.
I am now rethinking that, and wondering if it is just adding a bunch of extra characters/typing that don't really help in understanding.

This changes:
CallableContainerInterface -> CallableContainer
RunnableContainerInterface -> RunnableContainer
PrioritySchedulerInterface -> PrioritySchedulerService
SchedulerServiceInterface -> SchedulerService
SimpleSchedulerInterface -> SimpleScheduler
SubmitterExecutorInterface -> SubmitterExecutor
SubmitterSchedulerInterface -> SubmitterScheduler
ExceptionHandlerInterface -> ExceptionHandler

Right now this is fairly awkward to maintain backwards compatibility.  The old interfaces extend the new.  Where we accept implementations we accept the new interface (and since old extends new, this should be fine).  Where we implement an interface, or return an interface, we still return the old.  This is to ensure the old interface definitions would be assignable.

@lwahlmeier don't just merge this.  I want your opinion on which way is better.  Do you think a "Interface" suffix makes things easier to understand in the javadocs, or is it just extra typing?

### CODE REVIEW

**Comment by jentfoo** [comment]
The merge build failed due to a unit test.  If we are interested in this I will fix it before I merge

**Comment by lwahlmeier** [comment]
I have personally never been a fan of naming the type of item in the file name interface, abstract, and esp Impl all bother me a little in the class/file names, I think its pretty obvious to anyone who cares w/o it in the name and if its not they need to spend more time figuring out java in general. 

Wish there was an easier way to do this backwards compatible but I think its worth the change for 5.0

**Comment by jentfoo** [comment]
@lwahlmeier I have been leaning that way as well (though I do prefer the Abstract prefix for the time being).

This change is backwards compatible, obviously with things marked for removal in 5.X.

So I take it you think I should fix the unit test and merge this?

**Comment by jentfoo** [comment]
@lwahlmeier I updated the PR with a fixed build.  If you like this, go ahead and merge it.

https://threadly.ci.cloudbees.com/view/Threadly/job/threadly-master/599/

FWIW, this adds ~3KB to the jar, but that will be removed in the 5.0/0 release when we can remove the old X..Interface versions

**Pull request merged**
